@startuml IT-Wallet Onboarding System
left to right direction
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam packageStyle rectangle
skinparam ArrowColor #666666
skinparam ArrowFontSize 11
skinparam linetype ortho
skinparam nodesep 18
skinparam ranksep 45
skinparam rectangleBorderColor #333333
skinparam roundCorner 8
skinparam databaseBorderColor #333333
skinparam actorBorderColor #333333

package "IT-Wallet Onboarding System" {

  package "Registration" as pkgreg #F5F5F5 {
    rectangle "**National Federation Management**\n..\nAll Federation Entities,\nSubordinate Statements and Trust Marks" as fed #E3F2FD
    rectangle "**EUDIW Registration Management**\n..\nWallet-Relying Parties operating\nin the EUDIW Trust Framework" as reg #E3F2FD
    rectangle "**Authentic Source Management**\n..\nAuthentic Sources" as asmgr #E3F2FD
  }

  package "Certificate Issuance" as pkgcert #F5F5F5 {
    rectangle "**Certificate Management**\n..\nWRPAC, WRPRC, Sign/Seal and\nNational Authentication certificates" as x509 #E3F2FD
  }

  package "Attestation Management" as pkgatt #F5F5F5 {
    rectangle "**Claims and Schema Management**\n..\nClaims and Credential schemas" as schmgr #E3F2FD
    rectangle "**Catalog Management**\n..\nCredential types" as catmgr #E3F2FD
  }

  package "Notification" as pkgnot #F5F5F5 {
    rectangle "**Notification Dataset Management**\n..\nCategories subject to notification" as pub #E3F2FD
  }

  package "Registries and Data Stores" as pkgdata #F5F5F5 {

    package "Trust purpose" as pkgtrust #FFFFFF {
      database "Register\nof WRPs" as wrpreg #BBDEFB
      database "Federation API Endpoints,\nEntity Statements\nand Trust Marks" as fedreg #BBDEFB
    }

    package "Semantic and discovery purpose" as pkgsem #FFFFFF {
      database "National\nAS Registry" as asreg #C8E6C9
      database "National Claims /\nSchema Reg., Taxonomy" as reg3 #C8E6C9
      database "National\nCredentials Catalog" as cat #C8E6C9
    }

    database "Notification\nDataset" as notif #EEEEEE
  }
}

cloud "Attestation\nRulebook" as rb #EEEEEE
cloud "EUDIW Catalogue of Attributes\nand Catalogue of Schemes" as eucat #EEEEEE

' ---- rulebook reference ----
rb ..> pkgatt

' ---- component to store  ----
fed <--> fedreg
reg --> wrpreg
asmgr --> asreg
schmgr --> reg3
catmgr --> cat
pub --> notif

' ---- alignment with the EU catalogues ----
pkgsem ..> eucat 

' ---- certificate issuance ----
reg --> x509
x509 <-- fedreg 
x509 <-- wrpreg 

' ---- notifiable information ----
pkgreg --> pub

@enduml