#!/usr/bin/env python3

# -- PROJECT Variables ----------------------------------------------------
settings_project_name = "IT-Wallet Technical Specifications"
# Stable browser/tab title and header — not modified by CI preview suffixes.
settings_site_title = "IT-Wallet Technical Specifications"
# settings_copyright_copyleft = 'Dipartimento per la Trasformazione Digitale'
settings_editor_name = 'Dipartimento per la Trasformazione Digitale'
settings_doc_version = '1.4.6'
settings_doc_release = "versione-corrente"
settings_basename = 'eid-wallet-it-docs'
settings_file_name = 'eid-wallet-it-docs'

version = settings_doc_version

import sys, os
import shlex
import subprocess

from pathlib import Path
confdir = Path(__file__).resolve().parent
sys.path.insert(0, str(confdir.parent / 'common'))
from pdf_release_date import pdf_title_release_date, resolve_release_date_iso

# -- RTD configuration -------------------------------------------------

# on_rtd is whether we are on readthedocs.org, this line of code grabbed from docs.readthedocs.org
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

# This is used for linking and such so we link to the thing we're building
rtd_version = os.environ.get('READTHEDOCS_VERSION', 'latest')
if rtd_version not in ['stable', 'latest']:
    rtd_version = 'latest'

rtd_project = os.environ.get('READTHEDOCS_PROJECT', '')

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '7.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.imgconverter',
    'sphinxcontrib.redoc',
    'myst_parser',
    'sphinxcontrib.plantuml'
]

redoc = [
    {
        'name': 'OAS3-PDND-AS',
        'page': 'OAS3-PDND-AS',
        'spec': './oas3/OAS3-PDND-AS.yaml',
        'embed': True,
    },
    {
        'name': 'OAS3-PDND-WP',
        'page': 'OAS3-PDND-WP',
        'spec': './oas3/OAS3-PDND-WP.yaml',
        'embed': True,
    },
    {
        'name': 'OAS3-Register-API-READ',
        'page': 'OAS3-Register-API-READ',
        'spec': './oas3/OAS3-Register-API-READ.yaml',
        'embed': True,
    }
]


redoc_uri = 'https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js'
rst_epilog = """
.. _blank: target="_blank"
"""

plantuml_jar = confdir.parent.parent / "utils/plantuml/plantuml-1.2025.2.jar"
#plantuml = f'java -Djava.awt.headless=true -jar {shlex.quote(str(plantuml_jar))}'
plantuml = f'java -Djava.awt.headless=true -jar {str(plantuml_jar)}'
plantuml_output_format = 'svg'
plantuml_latex_output_format = 'pdf'
plantuml_server = ''
#plantuml_cache_path = './cache'

images_config = {
    "default_image_width": "99%",
    "align": "center"
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = ['.rst', '.md']

# The encoding of source files.
#source_encoding = 'utf-8-sig'
source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = settings_project_name
# copyright = settings_copyright_copyleft

# URL of Discourse instance used by sphinxcontrib.discourse extension
# discourse_url = settings_discourse_url

# ``version`` is already set from ``settings_doc_version`` near the top of this file.
# ``release`` is emitted into LaTeX as ``\\release{...}`` and shown on the PDF title page
# (second line under the title in ``\\sphinxmaketitle``). Keep ``settings_project_name``
# free of version suffixes; the version appears only in that subheading.
release = settings_doc_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

settings_doc_release_date = resolve_release_date_iso(confdir.parent.parent)
today = pdf_title_release_date(settings_doc_release_date, language)

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['.DS_Store', 'README', 'README.md', '.venv*', '.env*']

# Partials pulled in with `.. include::` by an aggregating page. Sphinx reads
# every .rst in the source dir as a standalone document, so without this they
# would be parsed twice (standalone + inlined): that duplicates their explicit
# labels, leaves their figures unnumbered for :numref:, and reports them as
# documents missing from a toctree. Excluding them here does NOT affect the
# `include` directive, which reads the files straight from disk.
# Note: sections of these files are labelled under the *including* page, i.e.
# `infrastructure-trust:<Section>` / `trust-evaluation:<Section>`.
exclude_patterns += [
    # included by infrastructure-trust.rst
    'trust-pki-architecture.rst',
    'x509-certificate-profile.rst',
    'trust-artifact-common.rst',
    'trust-artifact-eudiw.rst',
    'trust-artifact-oidfed.rst',
    'trust-management.rst',
    # included by trust-evaluation.rst
    'trust-evaluation-eudiw.rst',
    'trust-evaluation-oidfed.rst',
    'trust-override-rules.rst',
    # included by onboarding-system.rst
    'onboarding-lifecycle.rst',
    'onboarding-overview.rst',
    'onboarding-registration-model.rst',
    'onboarding-processes.rst',
    'onboarding-processes-entities.rst',
    'onboarding-processes-artifacts.rst',
    'onboarding-processes-credentials.rst',
    'onboarding-lifecycle.rst',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- myst-parser setup --------------------------------------------------------
# Configurazione per myst_parser che sostituisce recommonmark
myst_enable_extensions = [
    "colon_fence",
    "smartquotes",
    "replacements",
    "deflist",
]

# Configurazione simile ad AutoStructify di recommonmark
myst_heading_anchors = 3
myst_enable_auto_toc_tree = True
myst_update_mathjax = False

# -- Options for HTML output ----------------------------------------------
html_theme = 'eid-wallet-docs'
html_theme_path = ['../../themes']

html_theme_options = {
    "header_org_name": settings_editor_name,
    "header_project_name": settings_site_title,
    "header_logo_path": "shared-ui/img/IT-Wallet-Logo-Primary-BlueItalia.svg",
    "source_url": "https://github.com/italia/eudi-wallet-it-docs",
    "source_icon": "github",
    "alternate_lang": "it",
    "alternate_lang_label": "ITA",
    "alternate_lang_name": "Italiano",
}

html_css_files = [
    "eid-wallet-docs-fonts.css",
    "shared-ui/css/bootstrap-italia.min.css",
    "shared-ui/css/ita.min.css",
    "eid-wallet-docs-overrides.css",
]


# The name for this set of Sphinx documents. If None, it defaults to
# "<project> v<release> documentation".
html_title = settings_site_title

# A shorter title for the navigation bar. Default is the same as html_title.
# html_short_title = "IT-Wallet"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = "https://avatars.githubusercontent.com/u/15377824?s=48&v=4"

# The name of an image file (within the static path) to use as favicon of the
# docs. This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "https://avatars.githubusercontent.com/u/15377824?s=48&v=4"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../../static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = ["../common"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%d/%m/%Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# Permalink anchors next to headings (shown on hover/focus via theme CSS).
html_permalinks = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it. The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = settings_basename + 'doc'


# -- Options for LaTeX output ---------------------------------------------
latex_engine = 'lualatex'
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'sphinxsetup': r'''
        verbatimforcewraps=true,
        verbatimwithframe=false,
        verbatimwrapslines=true,
        verbatimhintsturnover=false
    ''',
    'preamble': r'''
        % Allow inclusion of PDF 1.6/1.7 images (default is 1.5)
        \pdfminorversion=7
        \usepackage{luatex85}
        \usepackage{polyglossia}
        \setmainlanguage{english}
        
        % -- Fix for fancyhdr warning --
        \setlength{\headheight}{14pt}
        \addtolength{\topmargin}{-2pt}
        
        % -- Geometry settings (note that sphinx already include Geometry pkg) --
        \geometry{margin=2.5cm,top=3cm,bottom=3cm}
        
        % -- handling overfull/underfull --
        \tolerance=9999
        \emergencystretch=4em
        \hbadness=10000
        \vbadness=10000
        \hfuzz=2pt
        \vfuzz=2pt

        \usepackage{adjustbox}
        \usepackage{fvextra}
        \usepackage{seqsplit}
        
        % -- prevent too big dim  --
        \maxdimen=16383.99999pt
        
        % -- improvement space interruption --
        \widowpenalty=10000
        \clubpenalty=10000
        \brokenpenalty=10000
        
        % -- Spacing --
        \linespread{1.2}
        
        % -- Header and footer --
        \renewcommand{\headrulewidth}{0.4pt}
        \renewcommand{\footrulewidth}{0.4pt}
        
        % -- Handling special characters --
        \makeatletter
        % temporally save the original command
        \let\original@includegraphics\includegraphics
        
        % Scale figures to fit page body (caption + image) and handle special chars
        \renewcommand{\includegraphics}[2][]{%
            \begingroup
            \catcode`\-=12\relax
            \catcode`\_=12\relax
            \adjustbox{max width=\linewidth,max height=0.76\textheight,keepaspectratio,center}{%
                \original@includegraphics[#1]{#2}%
            }%
            \endgroup
        }

        \@ifundefined{sphinxincludegraphics}{}{%
            \let\original@sphinxincludegraphics\sphinxincludegraphics
            \renewcommand{\sphinxincludegraphics}[2][]{%
                \begingroup
                \catcode`\-=12\relax
                \catcode`\_=12\relax
                \adjustbox{max width=\linewidth,max height=0.76\textheight,keepaspectratio,center}{%
                    \original@sphinxincludegraphics[#1]{#2}%
                }%
                \endgroup
            }%
        }
        \makeatother

        % Break long JWT/URL lines in code blocks at any character
        \RecustomVerbatimEnvironment{sphinxVerbatim}{Verbatim}{%
            breaklines=true,%
            breakanywhere=true,%
            breaksymbolleft={},%
            breaksymbolright={},%
            commandchars=\\\{\}%
        }
        \RecustomVerbatimEnvironment{sphinxVerbatim*}{Verbatim}{%
            breaklines=true,%
            breakanywhere=true,%
            breaksymbolleft={},%
            breaksymbolright={}%
        }

        % Pygments wraps long JWT strings in unbreakable boxes; seqsplit fixes that
        \makeatletter
        \def\PYG@do#1{%
            \PYG@bc{\PYG@tc{\PYG@ul{\PYG@it{\PYG@bf{\PYG@ff{\seqsplit{#1}}}}}}}%
        }

        % Narrow tables: smaller type and tighter columns improve line breaking
        \AtBeginEnvironment{longtable}{%
            \small%
            \setlength{\tabcolsep}{3.5pt}%
            \emergencystretch=4em%
        }
        \makeatother

        % -- Improvement for long verbatim  --
        \makeatletter
        \def\sphinx@verbatim@space{\leavevmode\kern.5\fontdimen2\font}
        \makeatother
    ''',
    'extrapackages': r'''
        % No extra pks is required 
    ''',
    'passoptionstopackages': r'''
        % Minimal options for xcolor if required
        \PassOptionsToPackage{table}{xcolor}
    ''',
    'fontpkg': r'''
        % Font setup for LuaLaTeX
        \usepackage{fontspec}
        \defaultfontfeatures{Ligatures=TeX}
        \setmainfont{Latin Modern Roman}
        \setsansfont{Latin Modern Sans}
        \setmonofont{DejaVu Sans Mono}[
            BoldFont={DejaVu Sans Mono Bold},
            ItalicFont={DejaVu Sans Mono Oblique},
            Scale=MatchLowercase,
        ]
        \newfontfamily\UnicodeFallbackFont{DejaVu Sans}[
            Scale=MatchLowercase,
        ]
        \usepackage{newunicodechar}
        \newunicodechar{↔}{{\UnicodeFallbackFont ↔}}
        \newunicodechar{ˌ}{{\UnicodeFallbackFont ˌ}}
        \newunicodechar{ˈ}{{\UnicodeFallbackFont ˈ}}
        \newunicodechar{ː}{{\UnicodeFallbackFont ː}}
        \newunicodechar{ɪ}{{\UnicodeFallbackFont ɪ}}
    ''',
}

# Label printed before ``release`` on the PDF title page (see sphinxmanual.cls).
latex_elements['releasename'] = 'Version'

# Additional latex conf
latex_show_pagerefs = True
latex_show_urls = 'no'
latex_use_parts = True
latex_domain_indices = True
latex_use_modindex = True
latex_table_style = ['booktabs']


# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
# author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', settings_file_name + '.tex', settings_project_name, " ", 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', settings_file_name, settings_project_name,
     [settings_editor_name], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
# dir menu entry, description, category)
texinfo_documents = [
  (
    'index',
    settings_file_name,
    settings_project_name,
    settings_project_name,
    settings_project_name,
    'Miscellaneous'
  )
]

numfig = True

# to turn smartquotes off and be able to use
smartquotes = False

autosectionlabel_prefix_document= True

# Add official_resources to static path so files are copied during build
# Note: Sphinx will automatically copy image files referenced in RST figures,
# but adding official_resources to html_static_path makes the entire folder
# accessible for direct downloads
html_static_path = ['../../static', '../../official_resources']

